'use client';
import {useEffect,useRef,useState,FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import ModulePageHeader from '../../components/ModulePageHeader';
import {formatCfa,RESTAURANT_NAME} from '../../lib/restaurant';
import './salle.css';
type Table={_id:string;number:number;name:string;capacity:number;active:boolean};
type Item={itemCode:string;name:string;variant?:string;qty:number;price:number};
type Ticket={_id:string;__v:number;orderNumber:string;diningTableId:string;tableNumber:number;covers:number;diningNotes:string;items:Item[];total:number;status:string;diningClosed:boolean;createdAt:string;payment?:{paidAt?:string;method?:string;refundedAt?:string}};
type Menu={itemCode:string;name:string;category:string;price:number;variants?:{label:string;price:number}[]};
type Data={tables:Table[];orders:Ticket[];menu:Menu[];role:string};
const labels:Record<string,string>={draft:'Brouillon',confirmed:'Envoyée en cuisine',preparing:'En préparation',ready:'Prête à servir',served:'Servie',completed:'Terminée',cancelled:'Annulée'};
const methods:Record<string,string>={cash:'Espèces',mobile_money:'Mobile Money',card:'Carte',transfer:'Virement'};
const blankTable={id:'',number:1,name:'',capacity:4,active:true};
export default function SallePage(){
 const router=useRouter();const [data,setData]=useState<Data|null>(null);const [selected,setSelected]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [history,setHistory]=useState(false);const [query,setQuery]=useState('');const [category,setCategory]=useState('');const [composer,setComposer]=useState(false);const [editing,setEditing]=useState<Ticket|null>(null);const [cart,setCart]=useState<Item[]>([]);const [covers,setCovers]=useState(1);const [notes,setNotes]=useState('');const [requestKey,setRequestKey]=useState('');const [variants,setVariants]=useState<Record<string,string>>({});
 const [tableForm,setTableForm]=useState(blankTable);const [configure,setConfigure]=useState(false);const [action,setAction]=useState<{type:string;ticket:Ticket}|null>(null);const [reason,setReason]=useState('');const [method,setMethod]=useState('cash');const [confirmed,setConfirmed]=useState(false);const [received,setReceived]=useState('');const [receipt,setReceipt]=useState<Ticket|null>(null);const dialog=useRef<HTMLDialogElement>(null);
 async function load(){try{const r=await fetch('/api/salle',{cache:'no-store'});if(r.status===401){router.replace('/login');return;}const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setError('');}catch(e){setError(e instanceof Error?e.message:'Chargement impossible.');}}
 useEffect(()=>{void load();const timer=setInterval(load,15000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(action)dialog.current?.showModal();else dialog.current?.close();},[action]);
 useEffect(()=>{if(receipt){window.print();}},[receipt]);
 async function mutate(path:string,body:unknown,http='POST'){const r=await fetch(path,{method:http,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Opération impossible.');return d;}
 const table=data?.tables.find(t=>t._id===selected);
 const open=(o:Ticket)=>!o.diningClosed&&o.status!=='cancelled';
 const tickets=data?.orders.filter(o=>o.diningTableId===selected&&(history?!open(o):open(o)))||[];
 const activeOrders=data?.orders.filter(open)||[];
 const total=cart.reduce((sum,i)=>sum+i.qty*i.price,0);
 function start(ticket:Ticket|null=null){setEditing(ticket);setCart(ticket?.items||[]);setCovers(ticket?.covers||1);setNotes(ticket?.diningNotes||'');setRequestKey(crypto.randomUUID());setComposer(true);setQuery('');setError('');}
 function pick(id:string){if(composer&&!window.confirm('Quitter la saisie ? Les modifications non enregistrées seront perdues.'))return;setComposer(false);setSelected(id);setHistory(false);}
 function add(item:Menu){const itemVariants=Array.isArray(item.variants)?item.variants:[];const variant=itemVariants.find(v=>v.label===variants[item.itemCode]);if(itemVariants.length&&!variant){setError('Choisissez une variante pour '+item.name);return;}setCart(current=>{const found=current.findIndex(i=>i.itemCode===item.itemCode&&i.variant===variant?.label);if(found>=0)return current.map((i,index)=>index===found?{...i,qty:Math.min(99,i.qty+1)}:i);return [...current,{itemCode:item.itemCode,name:item.name+(variant?' · '+variant.label:''),variant:variant?.label,qty:1,price:variant?.price??item.price}];});setError('');}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await mutate(editing?'/api/salle/orders/'+editing._id:'/api/salle/orders',{tableId:selected,requestKey,items:cart.map(i=>({itemCode:i.itemCode,variant:i.variant,qty:i.qty})),covers,notes,...(editing?{action:'edit',version:editing.__v}:{})},editing?'PATCH':'POST');setComposer(false);setMessage('Brouillon enregistré. Vous pouvez l’envoyer en cuisine.');await load();}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible.');}finally{setBusy(false);}}
 async function execute(type:string,ticket:Ticket){setBusy(true);setError('');try{await mutate('/api/salle/orders/'+ticket._id,{action:type,version:ticket.__v,reason,method,confirmed},'PATCH');setAction(null);setMessage(type==='pay'?'Paiement enregistré.':type==='send'?'Commande envoyée en cuisine.':type==='serve'?'Service confirmé.':'Ticket annulé.');await load();}catch(e){setError(e instanceof Error?e.message:'Opération impossible.');}finally{setBusy(false);}}
 async function saveTable(e:FormEvent){e.preventDefault();setBusy(true);try{await mutate('/api/salle/tables',tableForm);setConfigure(false);setMessage('Table enregistrée.');await load();}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible.');}finally{setBusy(false);}}
 return <main id="module-content" tabIndex={-1} className="salle-shell">
 <ModulePageHeader title="Commandes en salle" description="Organisez les tables, prenez les commandes et suivez le service jusqu’à l’encaissement." actions={<><button className="secondary-button" disabled={busy} onClick={()=>void load()}>Actualiser</button>{data?.role==='admin'&&<button className="salle-primary" onClick={()=>{setConfigure(!configure);setTableForm({...blankTable,number:Math.max(0,...data.tables.map(t=>t.number))+1});}}>Gérer les tables</button>}</>}/>
 {error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="salle-success" role="status">{message}</p>}
 {!data&&!error&&<p>Chargement de la salle…</p>}
 {configure&&<section className="salle-panel"><h2>Configuration des tables</h2><form className="salle-table-form" onSubmit={saveTable}><label>Table à modifier<select value={tableForm.id} onChange={e=>{const t=data?.tables.find(t=>t._id===e.target.value);setTableForm(t?{id:t._id,number:t.number,name:t.name,capacity:t.capacity,active:t.active}:blankTable);}}><option value="">Nouvelle table</option>{data?.tables.map(t=><option key={t._id} value={t._id}>Table {t.number} · {t.name}</option>)}</select></label><label>Numéro<input type="number" required min={1} max={999} value={tableForm.number} onChange={e=>setTableForm({...tableForm,number:Number(e.target.value)})}/></label><label>Nom<input required maxLength={60} value={tableForm.name} onChange={e=>setTableForm({...tableForm,name:e.target.value})} placeholder="Terrasse, fenêtre…"/></label><label>Places<input type="number" required min={1} max={100} value={tableForm.capacity} onChange={e=>setTableForm({...tableForm,capacity:Number(e.target.value)})}/></label><label>Statut<select value={String(tableForm.active)} onChange={e=>setTableForm({...tableForm,active:e.target.value==='true'})}><option value="true">En service</option><option value="false">Hors service</option></select></label><button className="salle-primary" disabled={busy}>Enregistrer</button></form><p className="muted">Une table occupée ne peut pas être modifiée. Mettez une table hors service pour la retirer du plan sans effacer son historique.</p></section>}
 <section className="salle-kpis"><article><span>Tables occupées</span><strong>{new Set(activeOrders.map(o=>o.diningTableId)).size} / {data?.tables.filter(t=>t.active).length||0}</strong></article><article><span>À servir</span><strong>{activeOrders.filter(o=>o.status==='ready').length}</strong></article><article><span>Reste à encaisser</span><strong>{formatCfa(activeOrders.filter(o=>!o.payment?.paidAt).reduce((sum,o)=>sum+o.total,0))}</strong></article></section>
 <div className="salle-workspace"><aside className="salle-panel"><h2>Plan des tables</h2><div className="salle-tables">{data?.tables.filter(t=>t.active).map(t=>{const orders=activeOrders.filter(o=>o.diningTableId===t._id);return <button key={t._id} className={(selected===t._id?'selected ':'')+(orders.length?'occupied':'')} onClick={()=>pick(t._id)} aria-pressed={selected===t._id}><strong>Table {t.number}</strong><span>{t.name} · {t.capacity} places</span><small>{orders.length?orders.length+' ticket(s) en cours':'Libre'}</small>{orders.some(o=>o.status==='ready')&&<b>À servir</b>}</button>;})}</div>{data&&!data.tables.some(t=>t.active)&&<p className="muted">Aucune table en service. {data.role==='admin'?'Ajoutez une table avec « Gérer les tables ».':'Demandez à un administrateur de configurer les tables.'}</p>}</aside>
 <section className="salle-detail">{!table?<div className="salle-panel salle-empty"><h2>Sélectionnez une table</h2><p>Ouvrez un ticket, ajoutez les plats et envoyez la commande en cuisine.</p></div>:<>
 <div className="salle-panel salle-detail-heading"><div><h2>Table {table.number} · {table.name}</h2><p>{table.capacity} places · {activeOrders.filter(o=>o.diningTableId===selected).length} ticket(s) en cours</p></div><button className="salle-primary" disabled={busy||composer||!table.active} onClick={()=>start()}>+ Nouveau ticket</button></div>
 {composer?<form className="salle-panel" onSubmit={save}><h2>{editing?'Modifier le brouillon':'Prendre une commande'}</h2><div className="salle-fields"><label>Couverts<input type="number" min={1} max={table.capacity} required value={covers} onChange={e=>setCovers(Number(e.target.value))}/></label><label>Consignes cuisine<textarea maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Cuisson, allergies signalées, service…"/></label></div><div className="salle-fields"><label>Rechercher un plat<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom du plat"/></label><label>Catégorie<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Toutes</option>{[...new Set(data?.menu.map(m=>m.category))].map(c=><option key={c}>{c}</option>)}</select></label></div>
 <div className="salle-menu">{data?.menu.filter(m=>(!category||m.category===category)&&m.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(m=><article key={m.itemCode}><strong>{m.name}</strong><small>{m.category}</small>{(m.variants?.length ?? 0) > 0 ? <select aria-label={'Variante de '+m.name} value={variants[m.itemCode]||''} onChange={e=>setVariants({...variants,[m.itemCode]:e.target.value})}><option value="">Choisir la taille</option>{(m.variants ?? []).map(v=><option key={v.label} value={v.label}>{v.label} · {formatCfa(v.price)}</option>)}</select> : <span>{formatCfa(m.price)}</span>}<button type="button" className="secondary-button" onClick={()=>add(m)} disabled={busy}>Ajouter</button></article>)}</div>
 <h3>Commande · {cart.length} ligne(s)</h3>{!cart.length&&<p className="muted">Ajoutez des plats depuis la carte.</p>}<div className="salle-cart">{cart.map((i,index)=><div key={i.itemCode+(i.variant||'')}><span>{i.name}<small>{formatCfa(i.price)} / unité</small></span><input aria-label={'Quantité '+i.name} type="number" min={1} max={99} required value={i.qty} onChange={e=>setCart(cart.map((item,n)=>n===index?{...item,qty:Number(e.target.value)}:item))}/><strong>{formatCfa(i.qty*i.price)}</strong><button type="button" aria-label={'Retirer '+i.name} onClick={()=>setCart(cart.filter((_,n)=>n!==index))}>×</button></div>)}</div><div className="salle-actions"><strong>Total : {formatCfa(total)}</strong><button type="button" className="secondary-button" disabled={busy} onClick={()=>{if(window.confirm('Abandonner la saisie non enregistrée ?'))setComposer(false);}}>Annuler la saisie</button><button className="salle-primary" disabled={busy||!cart.length}>{busy?'Enregistrement…':'Enregistrer le brouillon'}</button></div></form>:<>
 <div className="salle-tabs"><button className={!history?'active':''} onClick={()=>setHistory(false)}>Tickets en cours</button><button className={history?'active':''} onClick={()=>setHistory(true)}>Historique récent</button></div>
 {!tickets.length&&<p className="salle-panel muted">{history?'Aucun ticket dans les 50 dernières commandes clôturées.':'Aucun ticket en cours pour cette table.'}</p>}{tickets.map(t=><article className="salle-panel salle-ticket" key={t._id}><div className="salle-ticket-top"><div><h3>{t.orderNumber}</h3><small>{new Date(t.createdAt).toLocaleString('fr-FR')} · {t.covers} couvert(s)</small></div><span className={'salle-status '+t.status}>{t.payment?.paidAt?'Encaissée':labels[t.status]}</span></div><ul>{t.items.map((i,n)=><li key={n}><span>{i.qty} × {i.name}</span><strong>{formatCfa(i.qty*i.price)}</strong></li>)}</ul>{t.diningNotes&&<p className="salle-notes">Consignes : {t.diningNotes}</p>}<div className="salle-actions"><strong>{formatCfa(t.total)}</strong><button className="secondary-button" onClick={()=>{setReceipt(null);setTimeout(()=>setReceipt(t),0);}}>Imprimer la note</button>{t.status==='draft'&&<><button className="secondary-button" disabled={busy} onClick={()=>start(t)}>Modifier</button><button className="salle-primary" disabled={busy} onClick={()=>void execute('send',t)}>Envoyer en cuisine</button></>}{t.status==='ready'&&<button className="salle-primary" disabled={busy} onClick={()=>void execute('serve',t)}>Confirmer le service</button>}{t.status==='served'&&(!t.diningClosed)&&<button className="salle-primary" disabled={busy} onClick={()=>{setAction({type:'pay',ticket:t});setConfirmed(false);setMethod('cash');setReceived('');}}>Encaisser</button>}{['draft','confirmed'].includes(t.status)&&<button className="salle-danger" disabled={busy} onClick={()=>{setAction({type:'cancel',ticket:t});setReason('');}}>Annuler le ticket</button>}</div>{t.payment?.paidAt&&<small>Encaissé le {new Date(t.payment.paidAt).toLocaleString('fr-FR')} · {methods[t.payment.method||'']}{t.payment.refundedAt?' · Remboursé':''}</small>}</article>)}
 </> }</>}</section></div>
 <dialog ref={dialog} className="salle-dialog" aria-labelledby="salle-action-title" onCancel={e=>{if(busy)e.preventDefault();else setAction(null);}}><h2 id="salle-action-title">{action?.type==='pay'?'Enregistrer un encaissement':'Annuler un ticket'}</h2><p>{action?.ticket.orderNumber} · {formatCfa(action?.ticket.total||0)}</p><form onSubmit={e=>{e.preventDefault();if(action)void execute(action.type,action.ticket);}}>{action?.type==='pay'?<><label>Moyen de paiement<select value={method} onChange={e=>setMethod(e.target.value)}>{Object.entries(methods).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{method==='cash'&&<label>Espèces reçues (FCFA)<input type="number" min={action.ticket.total} step={1} required value={received} onChange={e=>setReceived(e.target.value)}/><small>Monnaie à rendre : {formatCfa(Math.max(0,Number(received)-action.ticket.total))}</small></label>}<label className="salle-check"><input type="checkbox" checked={confirmed} required onChange={e=>setConfirmed(e.target.checked)}/>Je confirme avoir reçu le paiement intégral.</label><p className="muted">Cette action enregistre un paiement reçu ; elle ne débite aucun compte.</p></>:<label>Motif d’annulation<textarea required minLength={3} maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label>}{error&&<p role="alert" className="form-error">{error}</p>}<div className="salle-actions"><button type="button" className="secondary-button" disabled={busy} onClick={()=>setAction(null)}>Retour</button><button className="salle-primary" disabled={busy}>Confirmer</button></div></form></dialog>
 {receipt&&<section className="salle-receipt"><h1>{RESTAURANT_NAME}</h1><h2>Note de commande · Table {receipt.tableNumber}</h2><p>{receipt.orderNumber} · {new Date(receipt.createdAt).toLocaleString('fr-FR')}</p>{receipt.items.map((i,n)=><p key={n}>{i.qty} × {i.name} — {formatCfa(i.price*i.qty)}</p>)}<h2>Total : {formatCfa(receipt.total)}</h2><p>{receipt.payment?.paidAt?'Payé · '+methods[receipt.payment.method||'']:'À régler'}</p></section>}
 </main>;
}
